### ISSUE TITLE
Can't require module using browserify

### ISSUE THREAD

**Issue by samueljun** [MyPureCloud/purecloud-webrtc-sdk#3]
When I try to require the 'purecloud-webrtc-sdk' package using browserify, I see an error stating that that the module is missing.

```js
// index.js
const PureCloudWebrtcSdk = require('purecloud-webrtc-sdk');

console.log(PureCloudWebrtcSdk);
```

```sh
Samuel:test-purecloud-webrtc-sdk $ browserify index.js -o bundle.js
Error: Cannot find module 'purecloud-webrtc-sdk' from '/Users/sjun/Uber/Code/test-purecloud-webrtc-sdk'
    at /Users/sjun/.nvm/versions/node/v6.10.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/sjun/.nvm/versions/node/v6.10.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/sjun/.nvm/versions/node/v6.10.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/sjun/.nvm/versions/node/v6.10.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/sjun/.nvm/versions/node/v6.10.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/sjun/.nvm/versions/node/v6.10.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Looking at the repo's package.json, I see that the "browser" field is set but the referenced file does not exist in the repo:

```json
  "main": "src/client.js",
  "browser": "web/purecloud-webrtc-sdk.js",
  "files": [
```

Looks like there's a missing prepublish step?

**Comment by xdumaine** [comment]
Thanks @samueljun I'll capture this one as well.

**Comment by xdumaine** [comment]
Will be resolved in v1.0.1 later today.
